version: "3.9"
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "kek"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./src/docker/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile # Убедитесь, что это указывает на ваш Dockerfile
    image: app:1.0.2 # Замените 1.0.0 на свою схему версионирования
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kek
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - postgres