spring:
  security:
    user:
      password: 1
      name: test1

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: db_ss
        jdbc:
          lob:
            non_contextual_creation: true

#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#
#  datasource:
#    url: jdbc:h2:mem:db_ss;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS db_ss;TRACE_LEVEL_FILE=4
#    driver-class-name: org.h2.Driver
#    username: root
#    password: 12345
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/kek
    username: root
    password: 123

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: db_ss

logging:
  level:
    org:
      hibernate:
      springframework:
        security=DEBUG:

server:
  port: 9000
